---

- name: Lookup OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: debian

- name: Install apache packages for RedHat
  yum: "name={{ item }} state=present"
  with_items: apache_pkgs
  when: ansible_os_family == 'RedHat'

- name: Install apache packages for Debian
  apt: "name={{ item }} state=present"
  with_items: apache_pkgs
  when: ansible_os_family == 'Debian'
  tags: debian

- name: Add graphite vhost
  template: src=etc/httpd/conf.d/graphite.conf.j2 dest=/etc/httpd/conf.d/graphite.conf
   owner=apache group=apache mode=0644
  notify:
    - reload httpd
