---
- name: Discover facts and group
  hosts: all
  user: '{{ ssh_user }}'
  sudo: yes
  vars:
    ssh_user: root
  tasks:
    - name: Group RedHat hosts
      group_by: key={{ ansible_os_family }}


- name: Configure RedHat hosts
  hosts: RedHat
  user: '{{ ssh_user }}'
  sudo: yes
  gather_facts: no
  vars:
    ssh_user: root
  roles:
    - roles/centos


- name: graphite
  hosts: graphite
  user: '{{ ssh_user }}'
  sudo: true
  gather_facts: no
  vars:
    ssh_user: root
  roles:
    - roles/apache
    - roles/graphite
